// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDependencies() {
  return window['go']['main']['App']['CheckDependencies']();
}

export function DetectPlatform(arg1) {
  return window['go']['main']['App']['DetectPlatform'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}
