// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDependencies():Promise<Record<string, boolean>>;

export function DetectPlatform(arg1:string):Promise<string>;

export function Download(arg1:main.DownloadOptions):Promise<main.DownloadResult>;
